//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITO_FSIN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FSINEntities1 : DbContext
    {
        public FSINEntities1()
            : base("name=FSINEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Custom> Custom { get; set; }
        public virtual DbSet<Medical_checkup> Medical_checkup { get; set; }
        public virtual DbSet<Prisoners> Prisoners { get; set; }
        public virtual DbSet<Report_on_procurement> Report_on_procurement { get; set; }
        public virtual DbSet<Staff_headquarters> Staff_headquarters { get; set; }
        public virtual DbSet<StaffHolidays> StaffHolidays { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
    }
}
