//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITO_FSIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_on_procurement
    {
        public int Id { get; set; }
        public int Idorder { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Custom Custom { get; set; }
    }
}
